-- DonasOS 1.1.15.15 - Parte 3: histórico simples de acessos
-- Execute uma vez no SQL Editor do Supabase.

create table if not exists public.site_access_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  created_at timestamptz not null default now()
);

create index if not exists site_access_events_created_at_idx
  on public.site_access_events (created_at desc);

alter table public.site_access_events enable row level security;

drop policy if exists "site_access_events_insert_public" on public.site_access_events;
create policy "site_access_events_insert_public"
  on public.site_access_events for insert
  to anon, authenticated
  with check (char_length(session_id) between 8 and 120);

drop policy if exists "site_access_events_read_public" on public.site_access_events;
create policy "site_access_events_read_public"
  on public.site_access_events for select
  to anon, authenticated
  using (true);

-- O Realtime Presence não precisa de tabela. Ele usa o canal donasos-loja-presenca.


-- Reforço de permissões para projetos em que as políticas existem,
-- mas a função anon ainda não recebeu privilégios da tabela/sequência.
grant usage on schema public to anon, authenticated;
grant select, insert on table public.site_access_events to anon, authenticated;
grant usage, select on sequence public.site_access_events_id_seq to anon, authenticated;
